// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdqVz3eJOGMwLlnXUIihZYE7sTg-JYMM',
    appId: '1:1002526021133:web:5ac0942db50bff2e4b2744',
    messagingSenderId: '1002526021133',
    projectId: 'privilegecare-7537a',
    authDomain: 'privilegecare-7537a.firebaseapp.com',
    databaseURL: 'https://privilegecare-7537a-default-rtdb.firebaseio.com',
    storageBucket: 'privilegecare-7537a.appspot.com',
    measurementId: 'G-6N3RB8W952',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBtoR6dQQIeLSuulEIT2x2MtTWsg-04q8',
    appId: '1:1002526021133:android:6f1d3e25612d4d464b2744',
    messagingSenderId: '1002526021133',
    projectId: 'privilegecare-7537a',
    databaseURL: 'https://privilegecare-7537a-default-rtdb.firebaseio.com',
    storageBucket: 'privilegecare-7537a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxhtSgExjTwHNY06pXkmSan0DHOEj2mM',
    appId: '1:1002526021133:ios:8b9eecb82eaa1fe34b2744',
    messagingSenderId: '1002526021133',
    projectId: 'privilegecare-7537a',
    databaseURL: 'https://privilegecare-7537a-default-rtdb.firebaseio.com',
    storageBucket: 'privilegecare-7537a.appspot.com',
    iosBundleId: 'com.syncQatar.privilegecare',
  );
}
